# Generated by Django 3.1.7 on 2021-02-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="profile_images/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_is_private",
            field=models.BooleanField(default=False),
        ),
    ]
