# Generated by Django 3.1.6 on 2021-02-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210224_0627"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_is_private",
        ),
    ]
