# Generated by Django 3.1.7 on 2021-02-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_user_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
