# Generated by Django 3.1.6 on 2021-03-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_auto_20210228_1014"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="cover_image",
            new_name="image",
        ),
    ]
